@extends('layouts.navbar')

@section('navbar')

<main id="main">
    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs">
        <div class="page-header d-flex align-items-center"
            style="background-image: url('assets/img/1200px-GKPI_Jemaat_Khusus_Pasar_Sipoholon.jpg')"></div>
        <nav>
            <div class="container">
                <ol>
                    <li><a href="{{ route('home.index') }}">Home</a></li>
                    <li>Berita Gereja</li>
                </ol>
            </div>
        </nav>
    </div>
    <!-- End Breadcrumbs -->

    <section class="sample-page">
        <div class="container" data-aos="fade-up">
            <div class="berita-header content">
                <h3>Berita Gereja Terbaru</h3>
            </div>
            {{-- konten --}}
            @foreach($berita as $item)
            <a href="{{ route('home.detailnews', ['id' => $item->id]) }}" class="text-decoration-none text-dark">
                <div class="card mb-3" style="cursor:pointer;">
                    <div class="row no-gutters">
                        <div class="col-md-4">
                            <img src="{{ $item->lampiran }}" class="card-img" alt="News Image" style="height: 270px; width: 100%; object-fit: cover;">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">{{ $item->judul }}</h5>
                                <p class="card-text">
                                    @php
                                    $words = explode(' ', $item->isi);
                                    $trimmed = implode(' ', array_slice($words, 0, 20));
                                    @endphp
                                    {{ $trimmed }}...
                                </p>
                                <p class="card-text">
                                    <small class="text-muted">
                                        <i class="bi bi-calendar-week"></i>
                                        {{ \Carbon\Carbon::parse($item->created_at)->isoFormat('D MMMM YYYY') }}
                                    </small>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
            @endforeach
            <!-- PAGINATION LINKS -->
            <div class="d-flex justify-content-center mt-4" id="pagination">
                <!-- Pagination content will be generated by JavaScript -->
            </div>
        </div>
    </section>

</main>
<!-- End #main -->

<script>
    var currentPage = {{ $berita->currentPage() }};
    var lastPage = {{ $berita->lastPage() }};
    var paginationElement = document.getElementById('pagination');

    // Function to generate pagination links
    function generatePagination() {
        var paginationHTML = '';

        // Previous page button
        paginationHTML += '<button class="btn btn-outline-primary mx-1"' +
            (currentPage === 1 ? ' disabled' : '') + ' onclick="navigateToPage(' + (currentPage - 1) + ')">&laquo;</button>';

        // Page numbers
        for (var i = 1; i <= lastPage; i++) {
            paginationHTML += '<button class="btn btn-outline-primary mx-1' +
                (i === currentPage ? ' active btn-primary' : '') + '" onclick="navigateToPage(' + i + ')">' + i + '</button>';
        }

        // Next page button
        paginationHTML += '<button class="btn btn-outline-primary mx-1"' +
            (currentPage === lastPage ? ' disabled' : '') + ' onclick="navigateToPage(' + (currentPage + 1) + ')">&raquo;</button>';

        paginationElement.innerHTML = paginationHTML;
    }

    // Function to navigate to a specific page
    function navigateToPage(page) {
        if (page >= 1 && page <= lastPage) {
            var url = new URL(window.location.href);
            url.searchParams.set('page', page);
            console.log('Navigating to page:', url.toString()); // Debug log
            window.location.href = url.toString();
        }
    }

    // Generate pagination on page load
    generatePagination();
</script>

@endsection
